"""Strict provider-neutral contracts for generated production plans."""

import math
from typing import Any, Literal

from pydantic import Field, field_validator, model_validator

from backend.src.production.application.sanitization import validate_safe_json
from backend.src.production.domain.base import ContractModel
from backend.src.production.planning.validation import validate_planning_text

SupportedAspectRatio = Literal["16:9", "9:16", "1:1"]


class PlanningJobConfiguration(ContractModel):
    """Public per-job options accepted by the planning capability."""

    language: str = Field(default="es", min_length=2, max_length=16)
    target_duration_seconds: float = Field(default=60.0, gt=0, le=3600)
    aspect_ratio: SupportedAspectRatio = "9:16"
    visual_style: str = Field(default="cinematic", min_length=1, max_length=200)
    narrative_style: str = Field(default="engaging", min_length=1, max_length=200)
    scene_count_hint: int = Field(default=4, ge=1, le=50)

    @field_validator("language", "visual_style", "narrative_style")
    @classmethod
    def validate_text(cls, value: str) -> str:
        return validate_planning_text(value)


class ProductionScenePlan(ContractModel):
    scene_number: int = Field(ge=1, le=50)
    title: str = Field(min_length=1, max_length=200)
    narration: str = Field(min_length=1, max_length=4000)
    visual_description: str = Field(min_length=1, max_length=2000)
    image_prompt: str = Field(min_length=1, max_length=2000)
    motion_instruction: str = Field(min_length=1, max_length=500)
    estimated_duration_seconds: float = Field(gt=0, le=600)
    transition: str = Field(min_length=1, max_length=100)
    on_screen_text: str | None = Field(default=None, max_length=500)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator(
        "title",
        "narration",
        "visual_description",
        "image_prompt",
        "motion_instruction",
        "transition",
        "on_screen_text",
    )
    @classmethod
    def validate_text(cls, value: str | None) -> str | None:
        return validate_planning_text(value) if value is not None else None

    @field_validator("metadata")
    @classmethod
    def validate_metadata(cls, value: dict[str, Any]) -> dict[str, Any]:
        validated = validate_safe_json(value, path="scene.metadata")
        if not isinstance(validated, dict):
            raise ValueError("scene metadata must be an object")
        return validated


class ProductionPlan(ContractModel):
    """Versioned output generated by any PlanningProvider implementation."""

    schema_version: str = Field(default="1.0.0", pattern=r"^\d+\.\d+\.\d+$")
    title: str = Field(min_length=1, max_length=300)
    summary: str = Field(min_length=1, max_length=2000)
    language: str = Field(min_length=2, max_length=16)
    target_duration_seconds: float = Field(gt=0, le=3600)
    aspect_ratio: SupportedAspectRatio
    visual_style: str = Field(min_length=1, max_length=200)
    narrative_style: str = Field(min_length=1, max_length=200)
    scenes: tuple[ProductionScenePlan, ...] = Field(min_length=1, max_length=50)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator(
        "title", "summary", "language", "visual_style", "narrative_style"
    )
    @classmethod
    def validate_text(cls, value: str) -> str:
        return validate_planning_text(value)

    @field_validator("metadata")
    @classmethod
    def validate_metadata(cls, value: dict[str, Any]) -> dict[str, Any]:
        validated = validate_safe_json(value, path="plan.metadata")
        if not isinstance(validated, dict):
            raise ValueError("plan metadata must be an object")
        return validated

    @model_validator(mode="after")
    def validate_scenes(self) -> "ProductionPlan":
        numbers = tuple(scene.scene_number for scene in self.scenes)
        if numbers != tuple(range(1, len(self.scenes) + 1)):
            raise ValueError("scene_number values must be consecutive starting at 1")
        total = sum(scene.estimated_duration_seconds for scene in self.scenes)
        if not math.isclose(total, self.target_duration_seconds, abs_tol=0.1):
            raise ValueError(
                "target_duration_seconds must equal the total estimated scene duration"
            )
        return self
