#!/usr/bin/env python3
"""Pipeline profiling and visualization script.

Generates performance reports identifying bottlenecks in the Orion AI pipeline.
Supports JSON, HTML, and markdown output formats.

Usage:
    python scripts/profile_pipeline.py [--output-dir=reports] [--format=html]
    python scripts/profile_pipeline.py --agent=vision --runs=10
"""

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

# Add backend to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from backend.src.infrastructure.profiler.performance_profiler import PerformanceProfiler
from backend.src.infrastructure.memory_manager.memory_manager import MemoryManager
from backend.src.infrastructure.checkpoint.checkpoint_manager import CheckpointManager
from backend.src.infrastructure.pipeline_cache.pipeline_cache import PipelineCache


def generate_html_report(profiler: PerformanceProfiler, output_path: Path) -> None:
    """Generate an interactive HTML profiling report."""
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orion AI Pipeline Profile</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2rem; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        h1 { color: #1a1a2e; border-bottom: 3px solid #16213e; padding-bottom: 0.5rem; }
        h2 { color: #16213e; margin-top: 2rem; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e0e0e0; }
        th { background: #16213e; color: white; font-weight: 600; }
        tr:hover { background: #f8f9fa; }
        .metric { display: inline-block; padding: 0.5rem 1rem; background: #e8f4f8; border-radius: 4px; margin: 0.25rem; font-weight: 500; }
        .bar { height: 24px; background: #16213e; border-radius: 4px; color: white; display: flex; align-items: center; padding-left: 0.5rem; font-size: 0.875rem; }
        .slow { background: #c0392b; }
        .medium { background: #f39c12; }
        .fast { background: #27ae60; }
        .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; color: #666; font-size: 0.875rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Orion AI Pipeline Performance Profile</h1>
        <p>Generated automatically by the CI/CD profiling stage.</p>
"""

    summary = profiler.get_summary()
    stages = summary.get("stages", [])
    html += f"""
        <h2>Pipeline Summary</h2>
        <div style="margin: 1rem 0;">
            <span class="metric">Total Stages: {summary.get('total_stages', 0)}</span>
            <span class="metric">Total Time: {summary.get('total_time_sec', 0):.2f}s</span>
            <span class="metric">Peak Memory: {summary.get('peak_memory_mb', 0):.1f} MB</span>
        </div>
"""

    if stages:
        html += """
        <h3>Stage Breakdown</h3>
        <table>
            <tr>
                <th>Stage</th>
                <th>Duration (s)</th>
                <th>% of Total</th>
                <th>CPU %</th>
                <th>Memory Δ (MB)</th>
                <th>Status</th>
            </tr>
"""
        total_time = summary.get("total_time_sec", 1)
        for stage in stages:
            pct = (stage["duration_sec"] / total_time * 100) if total_time > 0 else 0
            css_class = "slow" if pct > 40 else ("medium" if pct > 20 else "fast")
            cache_hit = stage.get("metadata", {}).get("cache_hit", False)
            html += f"""
            <tr>
                <td><strong>{stage['stage']}</strong></td>
                <td>{stage['duration_sec']:.3f}</td>
                <td><div class="bar {css_class}" style="width: {min(pct, 100):.1f}%">{pct:.1f}%</div></td>
                <td>{stage['cpu_percent']:.1f}%</td>
                <td>{stage['mem_delta_mb']:.1f}</td>
                <td>{'Cached' if cache_hit else 'Computed'}</td>
            </tr>
"""
        html += "</table>"

    html += """
        <div class="footer">
            <p>Orion AI &mdash; Profiling Report &mdash; Generated by CI/CD</p>
            <p>To improve performance, focus on stages marked in red (>40% of total time).</p>
        </div>
    </div>
</body>
</html>
"""

    output_path.write_text(html, encoding="utf-8")
    print(f"HTML report written to: {output_path}")


def generate_json_report(profiler: PerformanceProfiler, output_path: Path) -> None:
    """Generate a machine-readable JSON profiling report."""
    summary = profiler.get_summary()
    report = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "summary": summary,
    }
    output_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"JSON report written to: {output_path}")


def generate_markdown_report(profiler: PerformanceProfiler, output_path: Path) -> None:
    """Generate a markdown profiling report for PR comments."""
    summary = profiler.get_summary()
    stages = summary.get("stages", [])
    lines = [
        "# Orion AI Pipeline Performance Profile",
        "",
        f"**Generated:** {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}",
        "",
        "## Summary",
        "",
        f"- **Total Stages:** {summary.get('total_stages', 0)}",
        f"- **Total Time:** {summary.get('total_time_sec', 0):.2f}s",
        f"- **Peak Memory:** {summary.get('peak_memory_mb', 0):.1f} MB",
        "",
    ]

    if stages:
        lines += [
            "## Stage Breakdown",
            "",
            "| Stage | Duration | % Total | CPU % | Mem Δ |",
            "|-------|----------|---------|-------|-------|",
        ]
        total = summary.get("total_time_sec", 1)
        for stage in stages:
            pct = (stage["duration_sec"] / total * 100) if total > 0 else 0
            lines.append(
                f"| {stage['stage']} | {stage['duration_sec']:.3f}s | {pct:.1f}% | {stage['cpu_percent']:.1f}% | {stage['mem_delta_mb']:.1f}MB |"
            )
        lines += ["", "### Legend", "", "- 🔴 > 40% of total time (bottleneck)", "- 🟡 20-40% (moderate)", "- 🟢 < 20% (fast)", ""]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Markdown report written to: {output_path}")


def profile_simulated_run(profiler: PerformanceProfiler, memory: MemoryManager) -> None:
    """Simulate a pipeline run for profiling demo purposes."""
    from uuid import UUID
    run_id = UUID("12345678-1234-5678-1234-567812345678")
    memory.start_session(str(run_id))

    stages = [
        ("vision", "vision_agent"),
        ("audio", "audio_agent"),
        ("speech", "speech_agent"),
        ("video_understanding", "video_understanding"),
        ("viral_score", "viral_score"),
        ("creative_director", "creative_director"),
        ("consensus", "consensus_engine"),
        ("export", "exporter"),
    ]

    for name, agent in stages:
        handle = profiler.start_stage(name, run_id, agent_id=agent)
        time.sleep(0.01)  # Minimal real delay for demo
        profiler.end_stage(handle, metadata={"cache_hit": False})

    memory.end_session(str(run_id))


def main() -> int:
    parser = argparse.ArgumentParser(description="Orion AI Pipeline Profiler")
    parser.add_argument("--output-dir", default="profiling-reports", help="Directory for reports")
    parser.add_argument("--format", choices=["html", "json", "markdown", "all"], default="all", help="Report format")
    parser.add_argument("--simulate", action="store_true", help="Run a simulated profile for demo")
    args = parser.parse_args()

    output_dir = PROJECT_ROOT / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    profiler = PerformanceProfiler()
    memory = MemoryManager()

    if args.simulate:
        print("Running simulated pipeline profile...")
        profile_simulated_run(profiler, memory)

    # Always write reports based on current profiler state
    if args.format in ("json", "all"):
        generate_json_report(profiler, output_dir / "profile.json")
    if args.format in ("markdown", "all"):
        generate_markdown_report(profiler, output_dir / "profile.md")
    if args.format in ("html", "all"):
        generate_html_report(profiler, output_dir / "profile.html")

    print(f"\nProfiling reports generated in: {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
